/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SectoresRouteImport } from './routes/sectores'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as CapacidadesRouteImport } from './routes/capacidades'
import { Route as IndexRouteImport } from './routes/index'

const SectoresRoute = SectoresRouteImport.update({
  id: '/sectores',
  path: '/sectores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacidadesRoute = CapacidadesRouteImport.update({
  id: '/capacidades',
  path: '/capacidades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacidades': typeof CapacidadesRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/sectores': typeof SectoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacidades': typeof CapacidadesRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/sectores': typeof SectoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacidades': typeof CapacidadesRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/sectores': typeof SectoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capacidades' | '/nosotros' | '/proyectos' | '/sectores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capacidades' | '/nosotros' | '/proyectos' | '/sectores'
  id:
    | '__root__'
    | '/'
    | '/capacidades'
    | '/nosotros'
    | '/proyectos'
    | '/sectores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacidadesRoute: typeof CapacidadesRoute
  NosotrosRoute: typeof NosotrosRoute
  ProyectosRoute: typeof ProyectosRoute
  SectoresRoute: typeof SectoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sectores': {
      id: '/sectores'
      path: '/sectores'
      fullPath: '/sectores'
      preLoaderRoute: typeof SectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacidades': {
      id: '/capacidades'
      path: '/capacidades'
      fullPath: '/capacidades'
      preLoaderRoute: typeof CapacidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacidadesRoute: CapacidadesRoute,
  NosotrosRoute: NosotrosRoute,
  ProyectosRoute: ProyectosRoute,
  SectoresRoute: SectoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
